<?=$this->message; ?>
<? if($this->loggedin): ?>
    <?=$this->form; ?>
    <div id="view-content">
    <div class="noprint">
        <? if(isset($this->out)): ?>
        <a href="report/export">Экспорт в excel</a> | <a href="#" onClick="window.print();return false">Распечатать отчет</a><br>
        <? endif; ?>
    </div>

    <h1>Отчет ООО "РКУ", за месяц <?=$this->date; ?>, <?=$this->forWho; ?></h1>
    Всего распространено: <?=$this->sumAll; ?> <br>

    <? $pointer = 0;
    $end = false;
    ?>
    <? while ($end == false): ?>
    <h3>Столбцы: Дом/корпус -- количество -- не попал в подъезд</h3>
    <table <? if((count($this->out)-$pointer) < ($this->n*4)) {echo 'style="page-break-after:avoid"';} ?>>
        <tr>
            <td width="25%">
                <?
                for ($i=0; $i < $this->n; $i++): ?>
                    <p><? echo $this->out[$pointer]; $pointer++; ?></p>
                <? endfor;?>
            </td>
            <td width="25%">
                <? for ($i=0; $i < $this->n; $i++): ?>
                    <p><? echo $this->out[$pointer]; $pointer++; ?></p>
                <?endfor;?>
            </td>
            <td width="25%">
                <? for ($i=0; $i < $this->n; $i++): ?>
                    <p><? echo $this->out[$pointer]; $pointer++; ?></p>
                <?endfor;?>
            </td>
            <td width="25%">
                <? for ($i=0; $i < $this->n; $i++): ?>
                    <p><? echo $this->out[$pointer]; $pointer++; ?></p>
                <?endfor;
                if (!isset($this->out[$pointer]))
                    $end = true;
                ?>
            </td>
        </tr>
    </table>
    <div class="page-break"></div>
    <? endwhile; ?>
    </div>
<? endif; ?>