<?=$this->message; ?>

    <?=$this->form; ?>
    <div id="view-content">
    <div class="noprint">
        <?php if(isset($this->out)): ?>
        <a href="/report/exportbyday">Экспорт в excel</a> | <a href="#" onClick="window.print();return false">Распечатать отчет</a><br>
        <?php endif; ?>
    </div>

    <h1>Отчет ООО "РКУ", <?=$this->forWho; ?></h1>
    Всего распространено: <?=$this->sumAll; ?> <br>

    <?php $pointer = 0;    $end = false;    ?>
    
    <?php while ($end == false): ?>
    <h3>Столбцы: Дом/корпус -- количество -- не попал в подъезд</h3>
    <table <?php if((count($this->out)-$pointer) < ($this->n*4)) {echo 'style="page-break-after:avoid"';} ?>>
        <tr>
            <td width="25%">
                <?php for ($i=0; $i < $this->n; $i++): ?>
                    <p><?php echo $this->out[$pointer]; $pointer++; ?></p>
                <?php endfor;?>
            </td>
            <td width="25%">
                <?php for ($i=0; $i < $this->n; $i++): ?>
                    <p><?php echo $this->out[$pointer]; $pointer++; ?></p>
                <?php endfor;?>
            </td>
            <td width="25%">
                <?php for ($i=0; $i < $this->n; $i++): ?>
                    <p><?php echo $this->out[$pointer]; $pointer++; ?></p>
                <?php endfor;?>
            </td>
            <td width="25%">
                <?php for ($i=0; $i < $this->n; $i++): ?>
                    <p>
						<?php if(isset($this->out[$pointer]))
						{
							echo $this->out[$pointer]; $pointer++; 
						}?>
					</p>
                <?php endfor;
                if (!isset($this->out[$pointer]))
                    $end = true;
                ?>
            </td>
        </tr>
    </table>
    <div class="page-break"></div>
    <?php endwhile; ?>
    </div>

